backend:
  name: github
  repo: juanbucor-star/emsei-web
  branch: main
  auth_type: implicit
  app_id: Ov23lijkvgKWvnn5TQId

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: prueba
    label: Prueba
    files:
      - name: test_file
        label: Archivo de Prueba
        file: site_data/test_data.json
        fields:
          - { label: "TÃ­tulo de Prueba", name: "test_title", widget: string }